services:
  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - '11434:11434'
    volumes:
      - ollama:/root/.ollama
    expose:
      - 11434
    networks:
      - ollama
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - '3000:8080'
    volumes:
      - open-webui:/app/backend/data
    expose:
      - 3000
    networks:
      - ollama

volumes:
  open-webui:
  ollama:
networks:
  ollama: ~